- hosts: all
  become: true
  tasks:

   - name: install APT Transport HTTPS
     apt:
       name: apt-transport-https
       state: present
       
  - name: Install docker
    apt: 
      name: "{{ packages }}"
      state: present
      update_cache: yes
    vars:
      packages:
      - docker.io

  - name: Add administrador user to docker group
    user:
      name: administrador
      group: docker

  - name: Create .docker folder
    file:
      path: /home/administrador/.docker
      state: directory
    
  - name: Restart docker
    service:
      name: docker
      daemon_reload: yes
      state: restarted
    
  - name: Remove swapfile from /etc/fstab
    mount:
      name: "{{ item }}"
      fstype: swap
      state: absent
    with_items:
      - swap
      - none

  - name: Disable swap
    command: swapoff -a
    when: ansible_swaptotal_mb > 0

  - name: Add an apt signing key for Kubernetes
    apt_key:
      url: https://packages.cloud.google.com/apt/doc/apt-key.gpg
      state: present

  - name: Adding apt repository for Kubernetes
    apt_repository:
      repo: deb https://apt.kubernetes.io/ kubernetes-xenial main
      state: present
      filename: kubernetes.list

  - name: Install Kubernetes binaries
    apt: 
      name: "{{ packages }}"
      state: present
      update_cache: yes
    vars:
      packages:
        - kubelet 
        - kubeadm 
        - kubectl

  - name: Restart kubelet
    service:
      name: kubelet
      daemon_reload: yes
      state: restarted

  handlers:
    - name: docker status
      service: name=docker state=started  